config/routes.rb
Rails.application.routes.draw do
  root 'books#top'

  get 'books' => 'booklists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'books#top'

  post 'books' => 'booklists#create'

  get 'booklists' => 'booklists#index'

  get 'books/:id' => 'booklists#show', as: 'book'

  get 'books/:id/edit' => 'booklists#edit', as: 'edit_book'

  patch 'books/:id' => 'booklists#update', as: 'update_book'

  delete 'books/:id' => 'booklists#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booklists_controller.rb
class BooklistsController < ApplicationController
  def create
    book = Book.new(book_params)
    if book.save then
      redirect_to book_path(book.id), notice: "successfully"
    else
      @books = Book.order('id ASC')
      @book = book
      render :index
    end
  end

  def index
    @books = Book.order('id ASC')
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params) then
      redirect_to book_path(book.id), notice: "successfully"
    else
      @book = book
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to booklists_path, notice: "Book was successfully destroyed."
  end

  private

  def book_params
      params.require(:book).permit(:title, :body)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booklists_helper.rb
module BooklistsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/booklists/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="<%= "field_with_errors" if @book.errors.include?(:title) %>"><label>Title</label></div>
  <div class="<%= "field_with_errors" if @book.errors.include?(:title) %>"><%= f.text_field :title %></div>
  <div class="<%= "field_with_errors" if @book.errors.include?(:body) %>"><label>Body</label></div>
  <div class="<%= "field_with_errors" if @book.errors.include?(:body) %>"><%= f.text_area :body %></div>

  <p><%= f.submit 'Update Book' %></p>

  <p><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %></p>
<% end %>

app/views/booklists/index.html.erb
<%= notice %>
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%=book.title%>
        </td>
        <td>
          <%=book.body%>
        </td>
        <td>
          <%=link_to "Show", book_path(book.id) %>
        </td>
        <td>
          <%=link_to "Edit", edit_book_path(book.id) %>
        </td>
        <td>
          <%=link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="<%= "field_with_errors" if @book.errors.include?(:title) %>"><label>Title</label></div>
  <div class="<%= "field_with_errors" if @book.errors.include?(:title) %>"><%= f.text_field :title %></div>
  <div class="<%= "field_with_errors" if @book.errors.include?(:body) %>"><label>Body</label></div>
  <div class="<%= "field_with_errors" if @book.errors.include?(:body) %>"><%= f.text_area :body %></div>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/booklists/show.html.erb
<%= notice %>
<p><strong>Title:</strong> <%= @book.title %></p>
<p><strong>Body:</strong> <%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Back", books_path %>

app/views/books/top.html.erb
<!-- アプリケーショントップ画面 -->
<h1>ようこそ Bookers へ！</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<%=link_to 'start', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>